# docker-compose.yml เป็นไฟล์สำหรับรวมชุดคำสั่ง run container
version: "3"
services:
    # Mysql container 
    db:
        image: mysql:latest
        container_name: dolphin
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: banana
        networks: 
            - dev_network
    # PhpMyAdmin container
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        restart: always
        ports: 
            - '8080:80'
        environment: 
            #PMA_HOST: db #กำหนด server database
            #MYSQL_ROOT_PASSWORD: banana #กำหนดรหัสผ่านของ server database
            PMA_ARBITRARY: 1
        networks:
            - dev_network 
networks: 
    dev_network:
volumes:
    db_data: 


